# Generated by Django 3.1.13 on 2022-03-06 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='puesto',
            field=models.CharField(default='s', max_length=30),
            preserve_default=False,
        ),
    ]
