# Generated by Django 3.1.13 on 2022-03-27 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_puesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='S', max_length=20),
            preserve_default=False,
        ),
    ]
