# Generated by Django 3.1.13 on 2022-03-28 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220327_0417'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='unidad',
            field=models.CharField(default='s', max_length=50),
            preserve_default=False,
        ),
    ]
