# Generated by Django 3.1.13 on 2022-04-24 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0008_auto_20220306_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='eventmember',
            name='Comentario',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='line_presupuesto',
            name='Codigo',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterUniqueTogether(
            name='line_presupuesto',
            unique_together={('Proyecto', 'Codigo')},
        ),
    ]
